"""add otp auth

Revision ID: 2301b4592945
Revises: f92f11243217
Create Date: 2025-11-02 15:17:26.789526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2301b4592945'
down_revision = 'f92f11243217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_password',
    sa.Column('verification_code', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_one_time_password_id'), 'one_time_password', ['id'], unique=False)
    op.create_index(op.f('ix_one_time_password_verification_code'), 'one_time_password', ['verification_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_time_password_verification_code'), table_name='one_time_password')
    op.drop_index(op.f('ix_one_time_password_id'), table_name='one_time_password')
    op.drop_table('one_time_password')
    # ### end Alembic commands ###
