"""adapt user table to accept optional passwords

Revision ID: ff898cccdc22
Revises: 2301b4592945
Create Date: 2025-11-02 15:34:39.559385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff898cccdc22'
down_revision = '2301b4592945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # if confirmed is null set it to false
    op.execute("UPDATE person SET confirmed = FALSE WHERE confirmed IS NULL")
    op.alter_column('person', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute("UPDATE person SET first_name = '' WHERE first_name IS NULL")
    op.alter_column('person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.execute("UPDATE person SET last_name = '' WHERE last_name IS NULL")
    op.alter_column('person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
